name: librespot
base: core18
adopt-info: librespot
summary: Librespot is an open source client library for Spotify
description: |
  Librespot is an open source client library for Spotify written in Rust. It enables    
  applications to use Spotify's service to control and play music via various backends, 
  and to act as a Spotify Connect receiver. It is an alternative to the official and now 
  deprecated closed-source libspotify. Additionally, it will provide extra features which 
  are not available in the official library.
grade: stable
confinement: strict

#alsa fix from https://snapcraft-alsa.readthedocs.io/en/latest/snapcraft_usage.html
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

apps:
  librespot:
    command-chain: ["snap/command-chain/alsa-launch"]
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      ALWAYS_USE_PULSEAUDIO: '1'
      LC_ALL: "C.UTF-8"
    command: librespot
    plugs:
      - network
      - network-bind
      - unity7
      - audio-playback
      - pulseaudio
      - alsa


parts:
#issue with alsa > ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
#alsa fix from https://snapcraft-alsa.readthedocs.io/en/latest/snapcraft_usage.html
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
      
  librespot:
    plugin: rust
    source: https://github.com/librespot-org/librespot.git
    source-type: git
    source-branch: dev
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag -l --sort=version:refname | tail -n 1 | tr -d 'v')"
      echo $last_committed_tag
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      echo $last_released_tag
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "v${last_committed_tag}"
        echo "Setting version to $last_committed_tag"
        snapcraftctl set-version "$(echo $last_committed_tag)"
      else
        echo "Setting version to $(git rev-parse --short HEAD)"
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
    build-packages:
      - libasound2-dev
      - build-essential
      - pkg-config
      - libpulse-dev
    stage-packages:
      - libpulse0
    after:
      - alsa-mixin
